### ISSUE TITLE
Not presenting over UITabbar

### ISSUE THREAD

**Issue by kodekarim** [pNre/CoachMarks#1]
How to present it over UItabbar..?

**Comment by pNre** [comment]
Adding the `CoachmarkView` to the `UITabViewController` `view` should be enough.
Can you post an example project documenting your issue?

**Comment by kodekarim** [comment]
![group](https://cloud.githubusercontent.com/assets/13949425/24439136/f6eb8400-1469-11e7-8fdd-6195fa38c052.png)

Want to achieve the full page not beside the UITabbar

**Comment by pNre** [comment]
Are you presenting it from your "home" view or the tab bar controller view?

**Comment by kodekarim** [comment]
Home View @pNre

**Comment by pNre** [comment]
Most likely that's your problem, to have a view cover the tab bar you have to present it inside the UITabBarController view.
