### ISSUE TITLE
Problem to present in Navigation Controller

### ISSUE THREAD

**Issue by fabriciomasiero** [pNre/CoachMarks#2]
Hi, im attempting to present the CoachMark in NavigationController!

And i write this: 
        self.navigationController?.view.addSubview(coachmark)
        coachmark.translatesAutoresizingMaskIntoConstraints = false
        coachmark.leftAnchor.constraint(equalTo: view.leftAnchor).isActive = true
        coachmark.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        coachmark.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        coachmark.rightAnchor.constraint(equalTo: view.rightAnchor).isActive = true

But the console show me this error: *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutXAxisAnchor:0x60800126f880 "CoachMarks.CoachmarkView:0x7fe78bee92f0.left"> and <NSLayoutXAxisAnchor:0x60800126f900 "UIView:0x7fe78bee8df0.left"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'

Whats going on? Thanks

**Comment by pNre** [comment]
Have you tried placing the `coachmark` view inside the `view` of your `UINavigationController`'s `topViewController`?

**Comment by fabriciomasiero** [comment]
Hi, im tried to present in topViewController and app dont crash anymore, awesome!

But im want to present coachmark in my NavigationBar too, like coachmarking my barbutton items...

Check this image on attach


My code:

`self.navigationController?.topViewController?.view.addSubview(coachmark)
        coachmark.translatesAutoresizingMaskIntoConstraints = false
        coachmark.leftAnchor.constraint(equalTo: view.leftAnchor).isActive = true
        coachmark.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        coachmark.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        coachmark.rightAnchor.constraint(equalTo: view.rightAnchor).isActive = true`

`self.navigationItem.rightBarButtonItems = [self.btnBarSearch, self.btnBarFilter]
                coachmark.textLabel.textColor = .white
                coachmark.textLabel.text = "👋 this is a little example app showcasing some coach marks"
                coachmark.present(in: view, from: CGRect(x: self.btnBarFilter.buttonFrame().origin.x, y: 0, width: 40, height: 40), focusingOnElement: false)`



Thanks bro


![simulator screen shot 26 de jul de 2017 19 03 17](https://user-images.githubusercontent.com/2105842/28645886-7af80bd2-7235-11e7-9101-1a5d0bf553b7.png)

**Comment by pNre** [comment]
Got it, here:
```
self.navigationController?.view.addSubview(coachmark)
```
you are adding the coach mark as a subview of `navigationController?.view`.

And here:

```
coachmark.translatesAutoresizingMaskIntoConstraints = false
coachmark.leftAnchor.constraint(equalTo: view.leftAnchor).isActive = true
coachmark.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
coachmark.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
coachmark.rightAnchor.constraint(equalTo: view.rightAnchor).isActive = true
```

you are installing layout constraints between the coach mark and your view controller `view`.

To fix your issue just set the constraints between `coachmark` and `navigationController?.view` by writing something like this:

```
coachmark.translatesAutoresizingMaskIntoConstraints = false
coachmark.leftAnchor.constraint(equalTo: navigationController!.view.leftAnchor).isActive = true
coachmark.topAnchor.constraint(equalTo: navigationController!.iew.topAnchor).isActive = true
coachmark.bottomAnchor.constraint(equalTo: navigationController!.view.bottomAnchor).isActive = true
coachmark.rightAnchor.constraint(equalTo: navigationController!.view.rightAnchor).isActive = true
```

**Comment by fabriciomasiero** [comment]
Ohh, its works very well!! Thank you!!

One more question here, I swear =D

Why are some white corners appearing? I already tried to change the background color and other things, but nothing stopped them from appearing. If I use in my navigationController.topView these same white corners do not appear!


![simulator screen shot 31 de jul de 2017 15 18 08](https://user-images.githubusercontent.com/2105842/28791695-9d23212a-7603-11e7-950f-49bcfed423b3.png)




Doesnt matter the position, look this

![simulator screen shot 31 de jul de 2017 15 24 08](https://user-images.githubusercontent.com/2105842/28791927-638e3016-7604-11e7-8cc3-4347b10f6b61.png)

**Comment by pNre** [comment]
This is probably because the `from: CGRect` param you're passing to `coachmark.present(in:from:focusingOnElement:)` is too small.

Try adding some margin to it, try something like this:
```
coachmark.present(in: view, from: CGRect(x: self.btnBarFilter.buttonFrame().origin.x, y: 0, width: 40, height: 40).insetBy(dx: -5, dy: -5), focusingOnElement: false)
```

**Comment by fabriciomasiero** [comment]
Doesnt matter my insetBy, the white walkers (AKA white corners) continues appearing

**Comment by pNre** [comment]
Can you upload an example project having this issue?

**Comment by fabriciomasiero** [comment]
Yes, take a look 

[https://github.com/fabriciomasiero/CoachMarksExampleError](url)

Please, use iPhone 6s, cause the present CGRect are with hand values

**Comment by pNre** [comment]
Ok, I guess that's a bug. I'll push a fix as soon as possible.

**Comment by pNre** [comment]
Let me know if https://github.com/pNre/CoachMarks/commit/56fce70bc5d06646a4bb164f70dad4476e63e626 fixes the issue

**Comment by fabriciomasiero** [comment]
@pNre WORKS!!! Thanks bro!
