### ISSUE TITLE
Delegates Not Called

### ISSUE THREAD

**Issue by fabriciomasiero** [pNre/CoachMarks#3]
Hi,

I've tried to works with delegates, but i think its not working, neither in your example.

I've debugged your framework too, and apparently the delegate is nil when it's called. Or do I need to set the delegate programatically? I did not have access to property

Can you take a look? Thanks

**Comment by pNre** [comment]
For some reason I forgot to make the delegates public, have a look at https://github.com/pNre/CoachMarks/commit/509c2af5be1ce889c5e86180944acfc8877d7283
